ALTER TABLE `cis_wjzjl` 
MODIFY COLUMN `MESSID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '护士站消息返回id' AFTER `YLJGD`,
ADD COLUMN `YSMESSID` varchar(50) NULL COMMENT '医生站消息返回id' AFTER `MESSID`;